image: python:latest

services:
  - alias: ubuntu18
    name: rastasheep/ubuntu-sshd:18.04
  - alias: centos7
    name: indigodatacloud/centos-sshd:7

stages:
  - test
  - coverage
  - medium_test

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

#
# Use venv to test instruction in README
#
before_script:
  - which python
  - python -V
  - python -mvenv venv
  - source venv/bin/activate
  - which python
  - python -V
  - pip install .[dev]

python36:
  image: python:3.6
  stage: test
  script: tox -e py36

python37:
  image: python:3.7
  stage: test
  script: tox -e py37

cover37:
  image: python:3.7
  stage: coverage
  script:
    - coverage run --source sshkernel -m unittest
    - coverage html
    - coverage report
  artifacts:
    paths:
    - htmlcov
    expire_in: 1 month

run_papermill:
  image: python:3.7
  stage: medium_test
  script:
    - python ./test/setup.py
    - pip install papermill
    - pytest -s ./test/test_sshd_integration.py --disable-pytest-warnings
  artifacts:
    paths:
      - ./test/out
    expire_in: 1 week
